### ISSUE TITLE
3D scenes on both screens flicker non-stop

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#23]
id show a screenshot displaying the bug but ... theres really nothing to show , the game just doesnt seem to want to display

**Comment by vitor251093** [comment]
Can you give me an example of a moment in the game when both screens are showing 3D, so I can reproduce it?

**Comment by sandwichwater** [comment]
sure , the "vanquish the heartless threat" mission in olympus , happens during the cutscene you talk to phil and during the guard armour fight

**Comment by sandwichwater** [comment]
forgot to mention the screen is no longer black but now flickers between views _a lot_

**Comment by vitor251093** [comment]
@sandwichwater  I think this issue may also be already solved in the master branch build (new commits since v0.2.0). Could you please confirm?

**Comment by sandwichwater** [comment]
ah sorry for the late response , it doesnt flicker anymore but now its back to just displaying a pure black screen . ive run across a few new bugs as well , should i make new issues for those ¿

**Comment by vitor251093** [comment]
> it doesnt flicker anymore but now its back to just displaying a pure black screen , though this time it displays the top whenever the bottom screen shows up

That's weird. Oh well, I will access the missions you described back in June in order to figure out why this happened.

> ive run across a few new bugs as well , should i make new issues for those ¿

Yup. I've refactored the code after the merge of the latest melonDS commits, and, in order to avoid conflicts even more, I've moved the screen sizing logic to the shader. That was also how I managed to fix the background color bug after all this time.

I didn't got to see many bugs, other than the ones I fixed last night, but I'm not surprised that there are more.

**Comment by vitor251093** [comment]
I've solved the flicking effect by keeping both screens visible side by side all the time.

It still isn't ideal, but at least it shouldn't be seizure inducing.

Any attempt to give more focus to the first screen resulted in glitches. It seems that, during those double 3D scenes, melonDS OpenGL rendered only increased the scale on one of each two frames.

**Comment by sandwichwater** [comment]
hmm .. still getting the same results , just a black screen until the bottom screen shows up , though now when the bottom screen shows up i do see the side by side implementation but it goes away as soon as the bottom screen disappears . so bizarre

> It seems that, during those double 3D scenes, melonDS OpenGL rendered only increased the scale on one of each two frames.

this is just how melonds works for some reason , i dont know why but the emulator outputs two frames for every one frame of game render , which doesnt seem to happen on other emulators . im not sure why this is but i doubt it could be fixed without rewriting the whole renderer similar to the texture replacement issue with the compute shader renderer

**Comment by vitor251093** [comment]
> hmm .. still getting the same results , just a black screen until the bottom screen shows up , though now when the bottom screen shows up i do see the side by side implementation but it goes away as soon as the bottom screen disappears . so bizarre

That's strange. In which mission have you seen that? Mission 61?

> this is just how melonds works for some reason , i dont know why but the emulator outputs two frames for every one frame of game render , which doesnt seem to happen on other emulators . im not sure why this is but i doubt it could be fixed without rewriting the whole renderer similar to the texture replacement issue with the compute shader renderer

I figured it out. While rendering the top screen in fullscreen, ignoring the bottom screen, the UI size glitched between the current adapted size, and the original stretched format. And then, by removing the conditions that check if there is a 2D image on top of specific places, it started cropping the 3D image as if it was a 2D image. And then, by removing the 2D layer completely, I got to play as Sora, during the whole battle (even while the cutscene on the bottom screen was no longer there).

Considering they are using the same flow of the shader (which I can guarantee), this would only be possible if the top screen was actually rendered as 2D on top of the bottom screen. So both screens actually show the same thing, but the bottom screen ignores the 2D layer.

Why this glitch only happens in melonDS? I have no clue. Maybe it's because it tries to cut corners somewhere in order to allow the fps to be bigger than 30, or maybe the other emulators know this is a common workaround, so they ignore the frames with the rasterized top screen.

**Comment by vitor251093** [comment]
It seems Sora was appearing in a dark state because I was trying to create a merge of both screen, and each screen had a black 3D area on each frame, so it got dark. Using the 3D rendering straight away created that:

![Screenshot from 2024-02-08 21-31-28](https://github.com/vitor251093/KHDays_FM/assets/8976483/6126617c-d020-432b-915e-2612d3b16941)

**Comment by sandwichwater** [comment]
> That's strange. In which mission have you seen that? Mission 61?

seems to happen across every mission where dual screen 3d happens , this is what i see during dual screen scenes (nothing visibly shows happens until 0;16 due to the black screen lol , i figured id leave in the start of the scene anyway to help better document what happens)

https://github.com/vitor251093/KHDays_FM/assets/70611518/528b9580-ce55-4564-a068-a78af79f08a8

> It seems Sora was appearing in a dark state because I was trying to create a merge of both screen, and each screen had a black 3D area on each frame, so it got dark. Using the 3D rendering straight away created that:

hey now that is pretty cool to see ! super interesting

**Comment by vitor251093** [comment]
> seems to happen across every mission where dual screen 3d happens , this is what i see during dual screen scenes (nothing visibly shows happens until 0;16 due to the black screen lol , i figured id leave in the start of the scene anyway to help better document what happens)

Weird to see that happening with the master. Still, which mission exactly is that one from the video?

**Comment by sandwichwater** [comment]
mission 16 on day 51~ , eliminate the fire plants

**Comment by vitor251093** [comment]
I managed to make it no longer invisible, but it looks a bit unstable

**Comment by vitor251093** [comment]
I think I figured out the cause of this issue (being unstable).

When the DS needs to render both screens, it renders them in turns (in one frame, screen 1, in another frame, screen 2).

While I suppose other emulators handle that by just keeping the rendering of the prior frame and merging it with the current frame, melonDS takes a different approach, by rendering the prior frame in 2D ("screen capture"), and placing it on top of the new frame, keeping both screens visible. The drawback is that the 2D layer of melonDS has 256x192 pixels, which causes the visual instability by making it flick between the new resolution and the DS one.

It also doesn't seem to use the same shader during the screen capture, which makes the UI glitch in size as well in different dual-3D cutscenes.

It may be possible to fix that by making melonDS stack its frames instead of replacing them, while using the shader to produce a transparent image, and at the same time removing the use of the screen capture. Although, that's just a theory.

**Comment by vitor251093** [comment]
It seems I was right about my screen capture theory...

https://github.com/melonDS-emu/melonDS/issues/1496

It's indeed a melonDS issue. Still, it may be possible to fix it by reproducing the "screen ghosting" phenomenon with software.

**Comment by sandwichwater** [comment]
> (including the removal of melonDS's screen capture layer)

my only concern about this is removing screen capture of regular scenes outside of dual screen . some screen capture effects can be seen during the cutscene before the saix fight and the cutscene before the tailbunker fight

**Comment by vitor251093** [comment]
Sorry, I'd chosen my words poorly. I meant replacing the current screen capture system, which uses software rendering and produces an image with the original DS resolution, and instead, preserve whatever is on screen for another frame, so we won't have quality drops.

**Comment by sandwichwater** [comment]
ah no worries ! i understand now , that makes sense

**Comment by vitor251093** [comment]
Just had time to confirm, but based in the current focus of this ticket, this task is completed, since the flickering is gone. #71 will handle a more proper way of showing those screens, like mentioned above
